### ISSUE TITLE
Invalid Memory Access Problem on Windows

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip-tess4j#5]
see: http://tech.knime.org/forum/knime-image-processing/tess4j-node-execute-failed-invalid-memory-access

**Comment by Squareys** [comment]
I am currently recompiling tesseract with MinGW. It will result in a smaller binary (since I am building without Image I/O capabilities for tesseract. We have our own.) I will probably do the same for linux, which may result in more compatible distros and less shared object files.

**Comment by Squareys** [comment]
It seems, there may be some other issues with the Java to Tesseract conntection (/JNI Mapping), I will have another go at this next week.

**Comment by Squareys** [comment]
Alright! I worked hard to resolve this in the last few days.

The problem lies in the OCR Engine Mode . On Windows `Default` does not work, and there doesn't seem to be anything we could really do about that. On Linux we only get a random string.

I will try to find a solution for this tomorrow, otherwise we will disable that mode, update the example and release a new version of knip-tess4j with updated tesseract library versions and some other minor enhancements.

**Comment by Squareys** [comment]
The coming release `1.1.0` should fix this problem.
